Class&object
SergeenkovaAnna/dz_cycles pull request #5
Opened 2021-11-03 19:05 UTC by SergeenkovaAnna

Возможно попробую решить здания на уровень повыше и потом дослать

2021-11-03 20:48 UTC, DisterRU requested changes

2021-11-03 20:48 UTC, DisterRU commented on src/ru/skypro/lesson9/Author.java
> +    private String authorFirstName;
Нужно добавить модификатор final после private, так как поля не имеют сеттеров и не изменяются по ходе жизни программы.

Из имен переменных следует убрать слово author, т.к. и так понятна принадлежность этого поля, ведь оно находится внутри класса author.
Плюс к этому нужно задать этим двум полям имена "Имя" и "Фамилия".
В текущем варианте они имеют имена "Имя (название)" и "Имя".

2021-11-03 20:48 UTC, DisterRU commented on src/ru/skypro/lesson9/Book.java
> +    int publishingYear;
Поле должно быть private.

2021-11-03 20:48 UTC, DisterRU commented on src/ru/skypro/lesson9/Book.java
> +
Отсутствуют поля String name, Author author.

2021-11-03 20:48 UTC, DisterRU commented on src/ru/skypro/lesson9/Book.java
> +    }
Конструктор должен быть на три параметра.
Один уже имеется, два нужно добавить и в класс, и в конструктор.

2021-11-03 20:48 UTC, DisterRU commented on src/ru/skypro/Строки.java
Этого класса не должно быть в этом дз.
Нужно удалить и сделать коммит + пуш.

2021-11-04 16:46 UTC, SergeenkovaAnna commented on src/ru/skypro/lesson9/Book.java
> +    }
Почему их нельзя сделать в двух классах (имя и фамилия в классе Author, год издания в классе Book, а потом вызвать эти два конструктора в методе main в третьем классе, как я это сделала? Что принципиально поменяется?

2021-11-07 22:48 UTC, DisterRU commented on src/ru/skypro/lesson9/Book.java
> +    }
А где название книги?

2021-11-07 22:48 UTC, DisterRU commented on src/ru/skypro/lesson9/Book.java
> +    }
Имя и фамилия автора должны быть, безусловно, в авторе.

2021-11-07 22:50 UTC, DisterRU requested changes

2021-11-07 22:50 UTC, DisterRU commented on src/ru/skypro/lesson9/Author.java
> +    }
Использовать в геттерах this совершенно не требуется.
Это ключевое слово нужно в тех случаях, когда есть "затемнение" полей локальными переменными.

2021-11-07 22:50 UTC, DisterRU commented on src/ru/skypro/lesson9/Book.java
> +    private final String title;
Тут должно быть третье поле author, которое хранит в себе объект Author.
Объект author должен создаваться вне книги, а в книгу приходить в качестве параметра при создании (в конструкторе).
По итогу 3 поля: title, author и publishingYear.

2021-11-10 19:42 UTC, Avenirre approved these changes

2021-11-11 17:51 UTC, merged